version: '3'
services:
  postgres:
    image: postgres
    env_file:
      - ./docker/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./docker/pgadmin.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    env_file:
      - ./docker/backend.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile
    env_file:
      - ./docker/frontend.env
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres-data:
  pgadmin-data:
